version: "3.8"

networks:
  proxy-network:
    external: true

services:
  frontend:
    build: .
    container_name: infinityops-vue
    restart: always
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue.rule=Host(`infinityops.net`)"
      - "traefik.http.services.vue.loadbalancer.server.port=80"

